services:
  postgres:
    build:
      context: .
      dockerfile: postgres-dockerfile
    hostname: postgres
    user: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
