syntax = "proto3";
package tasks.v1;

import "tasks/v1/status.proto";
import "tasks/v1/addendums.proto";

import "google/protobuf/timestamp.proto";

option go_package = "github.com/WadeCappa/taskmaster/pkg/go/tasks/v1;taskspb";

service Tasks {
  rpc CreateTask(CreateTaskRequest) returns (CreateTaskResponse);
  rpc GetTasks(GetTasksRequest) returns (stream GetTasksResponse);
  rpc DescribeTask(DescribeTaskRequest) returns (DescribeTaskResponse);
  rpc SetTaskStatus(SetTaskStatusRequest) returns (SetTaskStatusResponse);
}

message CreateTaskRequest  {
  Task task = 1; 
}

message CreateTaskResponse {
  uint64 task_id = 1; 
}

message GetTasksRequest {
  Status status = 1;
}

message GetTasksResponse {
  Task task = 1;
}

message DescribeTaskRequest  {
  uint64 task_id = 1; 
}

message DescribeTaskResponse {
  Task task = 1;
  repeated uint64 blocked_by = 2;
  repeated Addendum addendums = 3;
}

message SetTaskStatusRequest {
  uint64 task_id = 1;
  Status status = 2;
}

message SetTaskStatusResponse {}

message Task {
  uint64 task_id = 1;
  string title = 2;
  string description = 3;
  // Only set the parent_task_id if this is a sub-task of another task
  uint64 parent_task_id = 4;
  Status status = 5;
  google.protobuf.Timestamp created_time = 6;
}
