// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.6
// source: tasks/v1/addendums.proto

package taskspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Addendums_AddAddendum_FullMethodName = "/tasks.v1.Addendums/AddAddendum"
)

// AddendumsClient is the client API for Addendums service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddendumsClient interface {
	AddAddendum(ctx context.Context, in *AddAddendumRequest, opts ...grpc.CallOption) (*AddAddendumResponse, error)
}

type addendumsClient struct {
	cc grpc.ClientConnInterface
}

func NewAddendumsClient(cc grpc.ClientConnInterface) AddendumsClient {
	return &addendumsClient{cc}
}

func (c *addendumsClient) AddAddendum(ctx context.Context, in *AddAddendumRequest, opts ...grpc.CallOption) (*AddAddendumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAddendumResponse)
	err := c.cc.Invoke(ctx, Addendums_AddAddendum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddendumsServer is the server API for Addendums service.
// All implementations must embed UnimplementedAddendumsServer
// for forward compatibility.
type AddendumsServer interface {
	AddAddendum(context.Context, *AddAddendumRequest) (*AddAddendumResponse, error)
	mustEmbedUnimplementedAddendumsServer()
}

// UnimplementedAddendumsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddendumsServer struct{}

func (UnimplementedAddendumsServer) AddAddendum(context.Context, *AddAddendumRequest) (*AddAddendumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAddendum not implemented")
}
func (UnimplementedAddendumsServer) mustEmbedUnimplementedAddendumsServer() {}
func (UnimplementedAddendumsServer) testEmbeddedByValue()                   {}

// UnsafeAddendumsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddendumsServer will
// result in compilation errors.
type UnsafeAddendumsServer interface {
	mustEmbedUnimplementedAddendumsServer()
}

func RegisterAddendumsServer(s grpc.ServiceRegistrar, srv AddendumsServer) {
	// If the following call panics, it indicates UnimplementedAddendumsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Addendums_ServiceDesc, srv)
}

func _Addendums_AddAddendum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAddendumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddendumsServer).AddAddendum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Addendums_AddAddendum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddendumsServer).AddAddendum(ctx, req.(*AddAddendumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Addendums_ServiceDesc is the grpc.ServiceDesc for Addendums service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Addendums_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tasks.v1.Addendums",
	HandlerType: (*AddendumsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAddendum",
			Handler:    _Addendums_AddAddendum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tasks/v1/addendums.proto",
}
