// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: tasks/v1/addendums.proto

package taskspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAddendumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAddendumRequest) Reset() {
	*x = AddAddendumRequest{}
	mi := &file_tasks_v1_addendums_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddendumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddendumRequest) ProtoMessage() {}

func (x *AddAddendumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_addendums_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddendumRequest.ProtoReflect.Descriptor instead.
func (*AddAddendumRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_addendums_proto_rawDescGZIP(), []int{0}
}

func (x *AddAddendumRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *AddAddendumRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddAddendumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAddendumResponse) Reset() {
	*x = AddAddendumResponse{}
	mi := &file_tasks_v1_addendums_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddendumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddendumResponse) ProtoMessage() {}

func (x *AddAddendumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_addendums_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddendumResponse.ProtoReflect.Descriptor instead.
func (*AddAddendumResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_addendums_proto_rawDescGZIP(), []int{1}
}

type Addendum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addendum) Reset() {
	*x = Addendum{}
	mi := &file_tasks_v1_addendums_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addendum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addendum) ProtoMessage() {}

func (x *Addendum) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_addendums_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addendum.ProtoReflect.Descriptor instead.
func (*Addendum) Descriptor() ([]byte, []int) {
	return file_tasks_v1_addendums_proto_rawDescGZIP(), []int{2}
}

func (x *Addendum) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Addendum) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

var File_tasks_v1_addendums_proto protoreflect.FileDescriptor

const file_tasks_v1_addendums_proto_rawDesc = "" +
	"\n" +
	"\x18tasks/v1/addendums.proto\x12\btasks.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\x12AddAddendumRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x15\n" +
	"\x13AddAddendumResponse\"c\n" +
	"\bAddendum\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12=\n" +
	"\fcreated_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime2W\n" +
	"\tAddendums\x12J\n" +
	"\vAddAddendum\x12\x1c.tasks.v1.AddAddendumRequest\x1a\x1d.tasks.v1.AddAddendumResponseB9Z7github.com/WadeCappa/taskmaster/pkg/go/tasks/v1;taskspbb\x06proto3"

var (
	file_tasks_v1_addendums_proto_rawDescOnce sync.Once
	file_tasks_v1_addendums_proto_rawDescData []byte
)

func file_tasks_v1_addendums_proto_rawDescGZIP() []byte {
	file_tasks_v1_addendums_proto_rawDescOnce.Do(func() {
		file_tasks_v1_addendums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_v1_addendums_proto_rawDesc), len(file_tasks_v1_addendums_proto_rawDesc)))
	})
	return file_tasks_v1_addendums_proto_rawDescData
}

var file_tasks_v1_addendums_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tasks_v1_addendums_proto_goTypes = []any{
	(*AddAddendumRequest)(nil),    // 0: tasks.v1.AddAddendumRequest
	(*AddAddendumResponse)(nil),   // 1: tasks.v1.AddAddendumResponse
	(*Addendum)(nil),              // 2: tasks.v1.Addendum
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_tasks_v1_addendums_proto_depIdxs = []int32{
	3, // 0: tasks.v1.Addendum.created_time:type_name -> google.protobuf.Timestamp
	0, // 1: tasks.v1.Addendums.AddAddendum:input_type -> tasks.v1.AddAddendumRequest
	1, // 2: tasks.v1.Addendums.AddAddendum:output_type -> tasks.v1.AddAddendumResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tasks_v1_addendums_proto_init() }
func file_tasks_v1_addendums_proto_init() {
	if File_tasks_v1_addendums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_v1_addendums_proto_rawDesc), len(file_tasks_v1_addendums_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_v1_addendums_proto_goTypes,
		DependencyIndexes: file_tasks_v1_addendums_proto_depIdxs,
		MessageInfos:      file_tasks_v1_addendums_proto_msgTypes,
	}.Build()
	File_tasks_v1_addendums_proto = out.File
	file_tasks_v1_addendums_proto_goTypes = nil
	file_tasks_v1_addendums_proto_depIdxs = nil
}
