// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.6
// source: tasks/v1/blockers.proto

package taskspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Blockers_AddBlocker_FullMethodName    = "/tasks.v1.Blockers/AddBlocker"
	Blockers_RemoveBlocker_FullMethodName = "/tasks.v1.Blockers/RemoveBlocker"
	Blockers_GetBlockers_FullMethodName   = "/tasks.v1.Blockers/GetBlockers"
)

// BlockersClient is the client API for Blockers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockersClient interface {
	AddBlocker(ctx context.Context, in *AddBlockerRequest, opts ...grpc.CallOption) (*AddBlockerResponse, error)
	RemoveBlocker(ctx context.Context, in *RemoveBlockerRequest, opts ...grpc.CallOption) (*RemoveBlockerResponse, error)
	GetBlockers(ctx context.Context, in *GetBlockersRequest, opts ...grpc.CallOption) (*GetBlockersResponse, error)
}

type blockersClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockersClient(cc grpc.ClientConnInterface) BlockersClient {
	return &blockersClient{cc}
}

func (c *blockersClient) AddBlocker(ctx context.Context, in *AddBlockerRequest, opts ...grpc.CallOption) (*AddBlockerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBlockerResponse)
	err := c.cc.Invoke(ctx, Blockers_AddBlocker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockersClient) RemoveBlocker(ctx context.Context, in *RemoveBlockerRequest, opts ...grpc.CallOption) (*RemoveBlockerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBlockerResponse)
	err := c.cc.Invoke(ctx, Blockers_RemoveBlocker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockersClient) GetBlockers(ctx context.Context, in *GetBlockersRequest, opts ...grpc.CallOption) (*GetBlockersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockersResponse)
	err := c.cc.Invoke(ctx, Blockers_GetBlockers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockersServer is the server API for Blockers service.
// All implementations must embed UnimplementedBlockersServer
// for forward compatibility.
type BlockersServer interface {
	AddBlocker(context.Context, *AddBlockerRequest) (*AddBlockerResponse, error)
	RemoveBlocker(context.Context, *RemoveBlockerRequest) (*RemoveBlockerResponse, error)
	GetBlockers(context.Context, *GetBlockersRequest) (*GetBlockersResponse, error)
	mustEmbedUnimplementedBlockersServer()
}

// UnimplementedBlockersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockersServer struct{}

func (UnimplementedBlockersServer) AddBlocker(context.Context, *AddBlockerRequest) (*AddBlockerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBlocker not implemented")
}
func (UnimplementedBlockersServer) RemoveBlocker(context.Context, *RemoveBlockerRequest) (*RemoveBlockerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBlocker not implemented")
}
func (UnimplementedBlockersServer) GetBlockers(context.Context, *GetBlockersRequest) (*GetBlockersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockers not implemented")
}
func (UnimplementedBlockersServer) mustEmbedUnimplementedBlockersServer() {}
func (UnimplementedBlockersServer) testEmbeddedByValue()                  {}

// UnsafeBlockersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockersServer will
// result in compilation errors.
type UnsafeBlockersServer interface {
	mustEmbedUnimplementedBlockersServer()
}

func RegisterBlockersServer(s grpc.ServiceRegistrar, srv BlockersServer) {
	// If the following call panics, it indicates UnimplementedBlockersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Blockers_ServiceDesc, srv)
}

func _Blockers_AddBlocker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlockerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockersServer).AddBlocker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blockers_AddBlocker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockersServer).AddBlocker(ctx, req.(*AddBlockerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockers_RemoveBlocker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBlockerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockersServer).RemoveBlocker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blockers_RemoveBlocker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockersServer).RemoveBlocker(ctx, req.(*RemoveBlockerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockers_GetBlockers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockersServer).GetBlockers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blockers_GetBlockers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockersServer).GetBlockers(ctx, req.(*GetBlockersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blockers_ServiceDesc is the grpc.ServiceDesc for Blockers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blockers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tasks.v1.Blockers",
	HandlerType: (*BlockersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBlocker",
			Handler:    _Blockers_AddBlocker_Handler,
		},
		{
			MethodName: "RemoveBlocker",
			Handler:    _Blockers_RemoveBlocker_Handler,
		},
		{
			MethodName: "GetBlockers",
			Handler:    _Blockers_GetBlockers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tasks/v1/blockers.proto",
}
