// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: tasks/v1/blockers.proto

package taskspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBlockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BlockedBy     uint64                 `protobuf:"varint,2,opt,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlockerRequest) Reset() {
	*x = AddBlockerRequest{}
	mi := &file_tasks_v1_blockers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlockerRequest) ProtoMessage() {}

func (x *AddBlockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_blockers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlockerRequest.ProtoReflect.Descriptor instead.
func (*AddBlockerRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_blockers_proto_rawDescGZIP(), []int{0}
}

func (x *AddBlockerRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *AddBlockerRequest) GetBlockedBy() uint64 {
	if x != nil {
		return x.BlockedBy
	}
	return 0
}

type AddBlockerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlockerResponse) Reset() {
	*x = AddBlockerResponse{}
	mi := &file_tasks_v1_blockers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlockerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlockerResponse) ProtoMessage() {}

func (x *AddBlockerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_blockers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlockerResponse.ProtoReflect.Descriptor instead.
func (*AddBlockerResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_blockers_proto_rawDescGZIP(), []int{1}
}

type RemoveBlockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BlockedBy     uint64                 `protobuf:"varint,2,opt,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlockerRequest) Reset() {
	*x = RemoveBlockerRequest{}
	mi := &file_tasks_v1_blockers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlockerRequest) ProtoMessage() {}

func (x *RemoveBlockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_blockers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlockerRequest.ProtoReflect.Descriptor instead.
func (*RemoveBlockerRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_blockers_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveBlockerRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RemoveBlockerRequest) GetBlockedBy() uint64 {
	if x != nil {
		return x.BlockedBy
	}
	return 0
}

type RemoveBlockerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlockerResponse) Reset() {
	*x = RemoveBlockerResponse{}
	mi := &file_tasks_v1_blockers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlockerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlockerResponse) ProtoMessage() {}

func (x *RemoveBlockerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_blockers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlockerResponse.ProtoReflect.Descriptor instead.
func (*RemoveBlockerResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_blockers_proto_rawDescGZIP(), []int{3}
}

type GetBlockersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockersRequest) Reset() {
	*x = GetBlockersRequest{}
	mi := &file_tasks_v1_blockers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockersRequest) ProtoMessage() {}

func (x *GetBlockersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_blockers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockersRequest.ProtoReflect.Descriptor instead.
func (*GetBlockersRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_blockers_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlockersRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetBlockersResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlockedByTaskIds []uint64               `protobuf:"varint,1,rep,packed,name=blocked_by_task_ids,json=blockedByTaskIds,proto3" json:"blocked_by_task_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBlockersResponse) Reset() {
	*x = GetBlockersResponse{}
	mi := &file_tasks_v1_blockers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockersResponse) ProtoMessage() {}

func (x *GetBlockersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_blockers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockersResponse.ProtoReflect.Descriptor instead.
func (*GetBlockersResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_blockers_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlockersResponse) GetBlockedByTaskIds() []uint64 {
	if x != nil {
		return x.BlockedByTaskIds
	}
	return nil
}

var File_tasks_v1_blockers_proto protoreflect.FileDescriptor

const file_tasks_v1_blockers_proto_rawDesc = "" +
	"\n" +
	"\x17tasks/v1/blockers.proto\x12\btasks.v1\"K\n" +
	"\x11AddBlockerRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x02 \x01(\x04R\tblockedBy\"\x14\n" +
	"\x12AddBlockerResponse\"N\n" +
	"\x14RemoveBlockerRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x02 \x01(\x04R\tblockedBy\"\x17\n" +
	"\x15RemoveBlockerResponse\"-\n" +
	"\x12GetBlockersRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"D\n" +
	"\x13GetBlockersResponse\x12-\n" +
	"\x13blocked_by_task_ids\x18\x01 \x03(\x04R\x10blockedByTaskIds2\xf1\x01\n" +
	"\bBlockers\x12G\n" +
	"\n" +
	"AddBlocker\x12\x1b.tasks.v1.AddBlockerRequest\x1a\x1c.tasks.v1.AddBlockerResponse\x12P\n" +
	"\rRemoveBlocker\x12\x1e.tasks.v1.RemoveBlockerRequest\x1a\x1f.tasks.v1.RemoveBlockerResponse\x12J\n" +
	"\vGetBlockers\x12\x1c.tasks.v1.GetBlockersRequest\x1a\x1d.tasks.v1.GetBlockersResponseB9Z7github.com/WadeCappa/taskmaster/pkg/go/tasks/v1;taskspbb\x06proto3"

var (
	file_tasks_v1_blockers_proto_rawDescOnce sync.Once
	file_tasks_v1_blockers_proto_rawDescData []byte
)

func file_tasks_v1_blockers_proto_rawDescGZIP() []byte {
	file_tasks_v1_blockers_proto_rawDescOnce.Do(func() {
		file_tasks_v1_blockers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_v1_blockers_proto_rawDesc), len(file_tasks_v1_blockers_proto_rawDesc)))
	})
	return file_tasks_v1_blockers_proto_rawDescData
}

var file_tasks_v1_blockers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tasks_v1_blockers_proto_goTypes = []any{
	(*AddBlockerRequest)(nil),     // 0: tasks.v1.AddBlockerRequest
	(*AddBlockerResponse)(nil),    // 1: tasks.v1.AddBlockerResponse
	(*RemoveBlockerRequest)(nil),  // 2: tasks.v1.RemoveBlockerRequest
	(*RemoveBlockerResponse)(nil), // 3: tasks.v1.RemoveBlockerResponse
	(*GetBlockersRequest)(nil),    // 4: tasks.v1.GetBlockersRequest
	(*GetBlockersResponse)(nil),   // 5: tasks.v1.GetBlockersResponse
}
var file_tasks_v1_blockers_proto_depIdxs = []int32{
	0, // 0: tasks.v1.Blockers.AddBlocker:input_type -> tasks.v1.AddBlockerRequest
	2, // 1: tasks.v1.Blockers.RemoveBlocker:input_type -> tasks.v1.RemoveBlockerRequest
	4, // 2: tasks.v1.Blockers.GetBlockers:input_type -> tasks.v1.GetBlockersRequest
	1, // 3: tasks.v1.Blockers.AddBlocker:output_type -> tasks.v1.AddBlockerResponse
	3, // 4: tasks.v1.Blockers.RemoveBlocker:output_type -> tasks.v1.RemoveBlockerResponse
	5, // 5: tasks.v1.Blockers.GetBlockers:output_type -> tasks.v1.GetBlockersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tasks_v1_blockers_proto_init() }
func file_tasks_v1_blockers_proto_init() {
	if File_tasks_v1_blockers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_v1_blockers_proto_rawDesc), len(file_tasks_v1_blockers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_v1_blockers_proto_goTypes,
		DependencyIndexes: file_tasks_v1_blockers_proto_depIdxs,
		MessageInfos:      file_tasks_v1_blockers_proto_msgTypes,
	}.Build()
	File_tasks_v1_blockers_proto = out.File
	file_tasks_v1_blockers_proto_goTypes = nil
	file_tasks_v1_blockers_proto_depIdxs = nil
}
