// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: tasks/v1/status.proto

package taskspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OPEN        Status = 0
	Status_IN_PROGRESS Status = 1
	Status_CLOSED      Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OPEN",
		1: "IN_PROGRESS",
		2: "CLOSED",
	}
	Status_value = map[string]int32{
		"OPEN":        0,
		"IN_PROGRESS": 1,
		"CLOSED":      2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_v1_status_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tasks_v1_status_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tasks_v1_status_proto_rawDescGZIP(), []int{0}
}

var File_tasks_v1_status_proto protoreflect.FileDescriptor

const file_tasks_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x15tasks/v1/status.proto\x12\btasks.v1*/\n" +
	"\x06Status\x12\b\n" +
	"\x04OPEN\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x02B9Z7github.com/WadeCappa/taskmaster/pkg/go/tasks/v1;taskspbb\x06proto3"

var (
	file_tasks_v1_status_proto_rawDescOnce sync.Once
	file_tasks_v1_status_proto_rawDescData []byte
)

func file_tasks_v1_status_proto_rawDescGZIP() []byte {
	file_tasks_v1_status_proto_rawDescOnce.Do(func() {
		file_tasks_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_v1_status_proto_rawDesc), len(file_tasks_v1_status_proto_rawDesc)))
	})
	return file_tasks_v1_status_proto_rawDescData
}

var file_tasks_v1_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tasks_v1_status_proto_goTypes = []any{
	(Status)(0), // 0: tasks.v1.Status
}
var file_tasks_v1_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tasks_v1_status_proto_init() }
func file_tasks_v1_status_proto_init() {
	if File_tasks_v1_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_v1_status_proto_rawDesc), len(file_tasks_v1_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tasks_v1_status_proto_goTypes,
		DependencyIndexes: file_tasks_v1_status_proto_depIdxs,
		EnumInfos:         file_tasks_v1_status_proto_enumTypes,
	}.Build()
	File_tasks_v1_status_proto = out.File
	file_tasks_v1_status_proto_goTypes = nil
	file_tasks_v1_status_proto_depIdxs = nil
}
