// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: tasks/v1/tasks.proto

package taskspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_DO_BEFORE_SLEEP Priority = 0
	Priority_DO_IMMEDIATELY  Priority = 1
	Priority_SHOULD_DO       Priority = 2
	Priority_EVENTUALLY_DO   Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "DO_BEFORE_SLEEP",
		1: "DO_IMMEDIATELY",
		2: "SHOULD_DO",
		3: "EVENTUALLY_DO",
	}
	Priority_value = map[string]int32{
		"DO_BEFORE_SLEEP": 0,
		"DO_IMMEDIATELY":  1,
		"SHOULD_DO":       2,
		"EVENTUALLY_DO":   3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_v1_tasks_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_tasks_v1_tasks_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_TRACKING  Status = 0
	Status_COMPLETED Status = 1
	Status_BACKLOG   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "TRACKING",
		1: "COMPLETED",
		2: "BACKLOG",
	}
	Status_value = map[string]int32{
		"TRACKING":  0,
		"COMPLETED": 1,
		"BACKLOG":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_v1_tasks_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tasks_v1_tasks_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{1}
}

type PutTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTaskRequest) Reset() {
	*x = PutTaskRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTaskRequest) ProtoMessage() {}

func (x *PutTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTaskRequest.ProtoReflect.Descriptor instead.
func (*PutTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *PutTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type PutTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTaskResponse) Reset() {
	*x = PutTaskResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTaskResponse) ProtoMessage() {}

func (x *PutTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTaskResponse.ProtoReflect.Descriptor instead.
func (*PutTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *PutTaskResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

// All fields are optional. For any given field, if nothing is provided then all tasks within
// that category are returned
type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=tasks.Status" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *GetTasksRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_TRACKING
}

func (x *GetTasksRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTasksResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DescribeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTaskRequest) Reset() {
	*x = DescribeTaskRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTaskRequest) ProtoMessage() {}

func (x *DescribeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTaskRequest.ProtoReflect.Descriptor instead.
func (*DescribeTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeTaskRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type DescribeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Addendum      []*Addendum            `protobuf:"bytes,2,rep,name=addendum,proto3" json:"addendum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTaskResponse) Reset() {
	*x = DescribeTaskResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTaskResponse) ProtoMessage() {}

func (x *DescribeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTaskResponse.ProtoReflect.Descriptor instead.
func (*DescribeTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *DescribeTaskResponse) GetAddendum() []*Addendum {
	if x != nil {
		return x.Addendum
	}
	return nil
}

type MarkTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTaskRequest) Reset() {
	*x = MarkTaskRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskRequest) ProtoMessage() {}

func (x *MarkTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskRequest.ProtoReflect.Descriptor instead.
func (*MarkTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *MarkTaskRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *MarkTaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MarkTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTaskResponse) Reset() {
	*x = MarkTaskResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskResponse) ProtoMessage() {}

func (x *MarkTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskResponse.ProtoReflect.Descriptor instead.
func (*MarkTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{7}
}

type GetTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{8}
}

type GetTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         uint64                 `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WriteTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=write_time,json=writeTime,proto3" json:"write_time,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsResponse) Reset() {
	*x = GetTagsResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsResponse) ProtoMessage() {}

func (x *GetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTagsResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *GetTagsResponse) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *GetTagsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTagsResponse) GetWriteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WriteTime
	}
	return nil
}

func (x *GetTagsResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Addendum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TimeCreated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_created,json=timeCreated,proto3" json:"time_created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addendum) Reset() {
	*x = Addendum{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addendum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addendum) ProtoMessage() {}

func (x *Addendum) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addendum.ProtoReflect.Descriptor instead.
func (*Addendum) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *Addendum) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Addendum) GetTimeCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeCreated
	}
	return nil
}

type Task struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinutesToComplete uint64                 `protobuf:"varint,2,opt,name=minutes_to_complete,json=minutesToComplete,proto3" json:"minutes_to_complete,omitempty"`
	Priority          Priority               `protobuf:"varint,3,opt,name=priority,proto3,enum=tasks.Priority" json:"priority,omitempty"`
	Status            Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=tasks.Status" json:"status,omitempty"`
	NumberOfAddendums uint64                 `protobuf:"varint,5,opt,name=numberOfAddendums,proto3" json:"numberOfAddendums,omitempty"`
	Tags              []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Prerequisites     []uint64               `protobuf:"varint,7,rep,packed,name=prerequisites,proto3" json:"prerequisites,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{11}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetMinutesToComplete() uint64 {
	if x != nil {
		return x.MinutesToComplete
	}
	return 0
}

func (x *Task) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_DO_BEFORE_SLEEP
}

func (x *Task) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_TRACKING
}

func (x *Task) GetNumberOfAddendums() uint64 {
	if x != nil {
		return x.NumberOfAddendums
	}
	return 0
}

func (x *Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Task) GetPrerequisites() []uint64 {
	if x != nil {
		return x.Prerequisites
	}
	return nil
}

type SetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=tasks.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusRequest) Reset() {
	*x = SetStatusRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusRequest) ProtoMessage() {}

func (x *SetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusRequest.ProtoReflect.Descriptor instead.
func (*SetStatusRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{12}
}

func (x *SetStatusRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetStatusRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_TRACKING
}

type SetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusResponse) Reset() {
	*x = SetStatusResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusResponse) ProtoMessage() {}

func (x *SetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusResponse.ProtoReflect.Descriptor instead.
func (*SetStatusResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{13}
}

var File_tasks_v1_tasks_proto protoreflect.FileDescriptor

const file_tasks_v1_tasks_proto_rawDesc = "" +
	"\n" +
	"\x14tasks/v1/tasks.proto\x12\x05tasks\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\x0ePutTaskRequest\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.tasks.TaskR\x04task\"*\n" +
	"\x0fPutTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"L\n" +
	"\x0fGetTasksRequest\x12%\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.tasks.StatusR\x06status\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"L\n" +
	"\x10GetTasksResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x1f\n" +
	"\x04task\x18\x02 \x01(\v2\v.tasks.TaskR\x04task\".\n" +
	"\x13DescribeTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"d\n" +
	"\x14DescribeTaskResponse\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.tasks.TaskR\x04task\x12+\n" +
	"\baddendum\x18\x02 \x03(\v2\x0f.tasks.AddendumR\baddendum\"D\n" +
	"\x0fMarkTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x12\n" +
	"\x10MarkTaskResponse\"\x10\n" +
	"\x0eGetTagsRequest\"\x8c\x01\n" +
	"\x0fGetTagsResponse\x12\x14\n" +
	"\x05tagId\x18\x01 \x01(\x04R\x05tagId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"write_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\twriteTime\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\"c\n" +
	"\bAddendum\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12=\n" +
	"\ftime_created\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vtimeCreated\"\x86\x02\n" +
	"\x04Task\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x13minutes_to_complete\x18\x02 \x01(\x04R\x11minutesToComplete\x12+\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x0f.tasks.PriorityR\bpriority\x12%\n" +
	"\x06status\x18\x04 \x01(\x0e2\r.tasks.StatusR\x06status\x12,\n" +
	"\x11numberOfAddendums\x18\x05 \x01(\x04R\x11numberOfAddendums\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12$\n" +
	"\rprerequisites\x18\a \x03(\x04R\rprerequisites\"R\n" +
	"\x10SetStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12%\n" +
	"\x06status\x18\x02 \x01(\x0e2\r.tasks.StatusR\x06status\"\x13\n" +
	"\x11SetStatusResponse*U\n" +
	"\bPriority\x12\x13\n" +
	"\x0fDO_BEFORE_SLEEP\x10\x00\x12\x12\n" +
	"\x0eDO_IMMEDIATELY\x10\x01\x12\r\n" +
	"\tSHOULD_DO\x10\x02\x12\x11\n" +
	"\rEVENTUALLY_DO\x10\x03*2\n" +
	"\x06Status\x12\f\n" +
	"\bTRACKING\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\x12\v\n" +
	"\aBACKLOG\x10\x022\x8e\x03\n" +
	"\x05tasks\x12:\n" +
	"\aPutTask\x12\x15.tasks.PutTaskRequest\x1a\x16.tasks.PutTaskResponse\"\x00\x12?\n" +
	"\bGetTasks\x12\x16.tasks.GetTasksRequest\x1a\x17.tasks.GetTasksResponse\"\x000\x01\x12I\n" +
	"\fDescribeTask\x12\x1a.tasks.DescribeTaskRequest\x1a\x1b.tasks.DescribeTaskResponse\"\x00\x12=\n" +
	"\bMarkTask\x12\x16.tasks.MarkTaskRequest\x1a\x17.tasks.MarkTaskResponse\"\x00\x12<\n" +
	"\aGetTags\x12\x15.tasks.GetTagsRequest\x1a\x16.tasks.GetTagsResponse\"\x000\x01\x12@\n" +
	"\tSetStatus\x12\x17.tasks.SetStatusRequest\x1a\x18.tasks.SetStatusResponse\"\x00B9Z7github.com/WadeCappa/taskmaster/pkg/go/tasks/v1;taskspbb\x06proto3"

var (
	file_tasks_v1_tasks_proto_rawDescOnce sync.Once
	file_tasks_v1_tasks_proto_rawDescData []byte
)

func file_tasks_v1_tasks_proto_rawDescGZIP() []byte {
	file_tasks_v1_tasks_proto_rawDescOnce.Do(func() {
		file_tasks_v1_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_v1_tasks_proto_rawDesc), len(file_tasks_v1_tasks_proto_rawDesc)))
	})
	return file_tasks_v1_tasks_proto_rawDescData
}

var file_tasks_v1_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tasks_v1_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tasks_v1_tasks_proto_goTypes = []any{
	(Priority)(0),                 // 0: tasks.Priority
	(Status)(0),                   // 1: tasks.Status
	(*PutTaskRequest)(nil),        // 2: tasks.PutTaskRequest
	(*PutTaskResponse)(nil),       // 3: tasks.PutTaskResponse
	(*GetTasksRequest)(nil),       // 4: tasks.GetTasksRequest
	(*GetTasksResponse)(nil),      // 5: tasks.GetTasksResponse
	(*DescribeTaskRequest)(nil),   // 6: tasks.DescribeTaskRequest
	(*DescribeTaskResponse)(nil),  // 7: tasks.DescribeTaskResponse
	(*MarkTaskRequest)(nil),       // 8: tasks.MarkTaskRequest
	(*MarkTaskResponse)(nil),      // 9: tasks.MarkTaskResponse
	(*GetTagsRequest)(nil),        // 10: tasks.GetTagsRequest
	(*GetTagsResponse)(nil),       // 11: tasks.GetTagsResponse
	(*Addendum)(nil),              // 12: tasks.Addendum
	(*Task)(nil),                  // 13: tasks.Task
	(*SetStatusRequest)(nil),      // 14: tasks.SetStatusRequest
	(*SetStatusResponse)(nil),     // 15: tasks.SetStatusResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_tasks_v1_tasks_proto_depIdxs = []int32{
	13, // 0: tasks.PutTaskRequest.task:type_name -> tasks.Task
	1,  // 1: tasks.GetTasksRequest.status:type_name -> tasks.Status
	13, // 2: tasks.GetTasksResponse.task:type_name -> tasks.Task
	13, // 3: tasks.DescribeTaskResponse.task:type_name -> tasks.Task
	12, // 4: tasks.DescribeTaskResponse.addendum:type_name -> tasks.Addendum
	16, // 5: tasks.GetTagsResponse.write_time:type_name -> google.protobuf.Timestamp
	16, // 6: tasks.Addendum.time_created:type_name -> google.protobuf.Timestamp
	0,  // 7: tasks.Task.priority:type_name -> tasks.Priority
	1,  // 8: tasks.Task.status:type_name -> tasks.Status
	1,  // 9: tasks.SetStatusRequest.status:type_name -> tasks.Status
	2,  // 10: tasks.tasks.PutTask:input_type -> tasks.PutTaskRequest
	4,  // 11: tasks.tasks.GetTasks:input_type -> tasks.GetTasksRequest
	6,  // 12: tasks.tasks.DescribeTask:input_type -> tasks.DescribeTaskRequest
	8,  // 13: tasks.tasks.MarkTask:input_type -> tasks.MarkTaskRequest
	10, // 14: tasks.tasks.GetTags:input_type -> tasks.GetTagsRequest
	14, // 15: tasks.tasks.SetStatus:input_type -> tasks.SetStatusRequest
	3,  // 16: tasks.tasks.PutTask:output_type -> tasks.PutTaskResponse
	5,  // 17: tasks.tasks.GetTasks:output_type -> tasks.GetTasksResponse
	7,  // 18: tasks.tasks.DescribeTask:output_type -> tasks.DescribeTaskResponse
	9,  // 19: tasks.tasks.MarkTask:output_type -> tasks.MarkTaskResponse
	11, // 20: tasks.tasks.GetTags:output_type -> tasks.GetTagsResponse
	15, // 21: tasks.tasks.SetStatus:output_type -> tasks.SetStatusResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_tasks_v1_tasks_proto_init() }
func file_tasks_v1_tasks_proto_init() {
	if File_tasks_v1_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_v1_tasks_proto_rawDesc), len(file_tasks_v1_tasks_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_v1_tasks_proto_goTypes,
		DependencyIndexes: file_tasks_v1_tasks_proto_depIdxs,
		EnumInfos:         file_tasks_v1_tasks_proto_enumTypes,
		MessageInfos:      file_tasks_v1_tasks_proto_msgTypes,
	}.Build()
	File_tasks_v1_tasks_proto = out.File
	file_tasks_v1_tasks_proto_goTypes = nil
	file_tasks_v1_tasks_proto_depIdxs = nil
}
