// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: tasks/v1/tasks.proto

package taskspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=tasks.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *GetTasksRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OPEN
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DescribeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTaskRequest) Reset() {
	*x = DescribeTaskRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTaskRequest) ProtoMessage() {}

func (x *DescribeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTaskRequest.ProtoReflect.Descriptor instead.
func (*DescribeTaskRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeTaskRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type DescribeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	BlockedBy     []uint64               `protobuf:"varint,2,rep,packed,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`
	Addendums     []*Addendum            `protobuf:"bytes,3,rep,name=addendums,proto3" json:"addendums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTaskResponse) Reset() {
	*x = DescribeTaskResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTaskResponse) ProtoMessage() {}

func (x *DescribeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTaskResponse.ProtoReflect.Descriptor instead.
func (*DescribeTaskResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *DescribeTaskResponse) GetBlockedBy() []uint64 {
	if x != nil {
		return x.BlockedBy
	}
	return nil
}

func (x *DescribeTaskResponse) GetAddendums() []*Addendum {
	if x != nil {
		return x.Addendums
	}
	return nil
}

type SetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=tasks.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskStatusRequest) Reset() {
	*x = SetTaskStatusRequest{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskStatusRequest) ProtoMessage() {}

func (x *SetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*SetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *SetTaskStatusRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SetTaskStatusRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OPEN
}

type SetTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskStatusResponse) Reset() {
	*x = SetTaskStatusResponse{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskStatusResponse) ProtoMessage() {}

func (x *SetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*SetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{7}
}

type Task struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TaskId      uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Only set the parent_task_id if this is a sub-task of another task
	ParentTaskId  uint64                 `protobuf:"varint,4,opt,name=parent_task_id,json=parentTaskId,proto3" json:"parent_task_id,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=tasks.v1.Status" json:"status,omitempty"`
	CreatedTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_tasks_v1_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_v1_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tasks_v1_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *Task) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetParentTaskId() uint64 {
	if x != nil {
		return x.ParentTaskId
	}
	return 0
}

func (x *Task) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OPEN
}

func (x *Task) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

var File_tasks_v1_tasks_proto protoreflect.FileDescriptor

const file_tasks_v1_tasks_proto_rawDesc = "" +
	"\n" +
	"\x14tasks/v1/tasks.proto\x12\btasks.v1\x1a\x15tasks/v1/status.proto\x1a\x18tasks/v1/addendums.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\x11CreateTaskRequest\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.tasks.v1.TaskR\x04task\"-\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\";\n" +
	"\x0fGetTasksRequest\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.tasks.v1.StatusR\x06status\"6\n" +
	"\x10GetTasksResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.tasks.v1.TaskR\x04task\".\n" +
	"\x13DescribeTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"\x8b\x01\n" +
	"\x14DescribeTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.tasks.v1.TaskR\x04task\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x02 \x03(\x04R\tblockedBy\x120\n" +
	"\taddendums\x18\x03 \x03(\v2\x12.tasks.v1.AddendumR\taddendums\"Y\n" +
	"\x14SetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.tasks.v1.StatusR\x06status\"\x17\n" +
	"\x15SetTaskStatusResponse\"\xe6\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0eparent_task_id\x18\x04 \x01(\x04R\fparentTaskId\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.tasks.v1.StatusR\x06status\x12=\n" +
	"\fcreated_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime2\xb6\x02\n" +
	"\x05Tasks\x12G\n" +
	"\n" +
	"CreateTask\x12\x1b.tasks.v1.CreateTaskRequest\x1a\x1c.tasks.v1.CreateTaskResponse\x12C\n" +
	"\bGetTasks\x12\x19.tasks.v1.GetTasksRequest\x1a\x1a.tasks.v1.GetTasksResponse0\x01\x12M\n" +
	"\fDescribeTask\x12\x1d.tasks.v1.DescribeTaskRequest\x1a\x1e.tasks.v1.DescribeTaskResponse\x12P\n" +
	"\rSetTaskStatus\x12\x1e.tasks.v1.SetTaskStatusRequest\x1a\x1f.tasks.v1.SetTaskStatusResponseB9Z7github.com/WadeCappa/taskmaster/pkg/go/tasks/v1;taskspbb\x06proto3"

var (
	file_tasks_v1_tasks_proto_rawDescOnce sync.Once
	file_tasks_v1_tasks_proto_rawDescData []byte
)

func file_tasks_v1_tasks_proto_rawDescGZIP() []byte {
	file_tasks_v1_tasks_proto_rawDescOnce.Do(func() {
		file_tasks_v1_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_v1_tasks_proto_rawDesc), len(file_tasks_v1_tasks_proto_rawDesc)))
	})
	return file_tasks_v1_tasks_proto_rawDescData
}

var file_tasks_v1_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tasks_v1_tasks_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),     // 0: tasks.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 1: tasks.v1.CreateTaskResponse
	(*GetTasksRequest)(nil),       // 2: tasks.v1.GetTasksRequest
	(*GetTasksResponse)(nil),      // 3: tasks.v1.GetTasksResponse
	(*DescribeTaskRequest)(nil),   // 4: tasks.v1.DescribeTaskRequest
	(*DescribeTaskResponse)(nil),  // 5: tasks.v1.DescribeTaskResponse
	(*SetTaskStatusRequest)(nil),  // 6: tasks.v1.SetTaskStatusRequest
	(*SetTaskStatusResponse)(nil), // 7: tasks.v1.SetTaskStatusResponse
	(*Task)(nil),                  // 8: tasks.v1.Task
	(Status)(0),                   // 9: tasks.v1.Status
	(*Addendum)(nil),              // 10: tasks.v1.Addendum
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_tasks_v1_tasks_proto_depIdxs = []int32{
	8,  // 0: tasks.v1.CreateTaskRequest.task:type_name -> tasks.v1.Task
	9,  // 1: tasks.v1.GetTasksRequest.status:type_name -> tasks.v1.Status
	8,  // 2: tasks.v1.GetTasksResponse.task:type_name -> tasks.v1.Task
	8,  // 3: tasks.v1.DescribeTaskResponse.task:type_name -> tasks.v1.Task
	10, // 4: tasks.v1.DescribeTaskResponse.addendums:type_name -> tasks.v1.Addendum
	9,  // 5: tasks.v1.SetTaskStatusRequest.status:type_name -> tasks.v1.Status
	9,  // 6: tasks.v1.Task.status:type_name -> tasks.v1.Status
	11, // 7: tasks.v1.Task.created_time:type_name -> google.protobuf.Timestamp
	0,  // 8: tasks.v1.Tasks.CreateTask:input_type -> tasks.v1.CreateTaskRequest
	2,  // 9: tasks.v1.Tasks.GetTasks:input_type -> tasks.v1.GetTasksRequest
	4,  // 10: tasks.v1.Tasks.DescribeTask:input_type -> tasks.v1.DescribeTaskRequest
	6,  // 11: tasks.v1.Tasks.SetTaskStatus:input_type -> tasks.v1.SetTaskStatusRequest
	1,  // 12: tasks.v1.Tasks.CreateTask:output_type -> tasks.v1.CreateTaskResponse
	3,  // 13: tasks.v1.Tasks.GetTasks:output_type -> tasks.v1.GetTasksResponse
	5,  // 14: tasks.v1.Tasks.DescribeTask:output_type -> tasks.v1.DescribeTaskResponse
	7,  // 15: tasks.v1.Tasks.SetTaskStatus:output_type -> tasks.v1.SetTaskStatusResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_tasks_v1_tasks_proto_init() }
func file_tasks_v1_tasks_proto_init() {
	if File_tasks_v1_tasks_proto != nil {
		return
	}
	file_tasks_v1_status_proto_init()
	file_tasks_v1_addendums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_v1_tasks_proto_rawDesc), len(file_tasks_v1_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_v1_tasks_proto_goTypes,
		DependencyIndexes: file_tasks_v1_tasks_proto_depIdxs,
		MessageInfos:      file_tasks_v1_tasks_proto_msgTypes,
	}.Build()
	File_tasks_v1_tasks_proto = out.File
	file_tasks_v1_tasks_proto_goTypes = nil
	file_tasks_v1_tasks_proto_depIdxs = nil
}
