// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.6
// source: tasks/v1/tasks.proto

package taskspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tasks_PutTask_FullMethodName      = "/tasks.tasks/PutTask"
	Tasks_GetTasks_FullMethodName     = "/tasks.tasks/GetTasks"
	Tasks_DescribeTask_FullMethodName = "/tasks.tasks/DescribeTask"
	Tasks_MarkTask_FullMethodName     = "/tasks.tasks/MarkTask"
	Tasks_GetTags_FullMethodName      = "/tasks.tasks/GetTags"
	Tasks_SetStatus_FullMethodName    = "/tasks.tasks/SetStatus"
)

// TasksClient is the client API for Tasks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TasksClient interface {
	PutTask(ctx context.Context, in *PutTaskRequest, opts ...grpc.CallOption) (*PutTaskResponse, error)
	GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTasksResponse], error)
	DescribeTask(ctx context.Context, in *DescribeTaskRequest, opts ...grpc.CallOption) (*DescribeTaskResponse, error)
	MarkTask(ctx context.Context, in *MarkTaskRequest, opts ...grpc.CallOption) (*MarkTaskResponse, error)
	GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTagsResponse], error)
	SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*SetStatusResponse, error)
}

type tasksClient struct {
	cc grpc.ClientConnInterface
}

func NewTasksClient(cc grpc.ClientConnInterface) TasksClient {
	return &tasksClient{cc}
}

func (c *tasksClient) PutTask(ctx context.Context, in *PutTaskRequest, opts ...grpc.CallOption) (*PutTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutTaskResponse)
	err := c.cc.Invoke(ctx, Tasks_PutTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTasksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tasks_ServiceDesc.Streams[0], Tasks_GetTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetTasksRequest, GetTasksResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tasks_GetTasksClient = grpc.ServerStreamingClient[GetTasksResponse]

func (c *tasksClient) DescribeTask(ctx context.Context, in *DescribeTaskRequest, opts ...grpc.CallOption) (*DescribeTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeTaskResponse)
	err := c.cc.Invoke(ctx, Tasks_DescribeTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) MarkTask(ctx context.Context, in *MarkTaskRequest, opts ...grpc.CallOption) (*MarkTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkTaskResponse)
	err := c.cc.Invoke(ctx, Tasks_MarkTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksClient) GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTagsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tasks_ServiceDesc.Streams[1], Tasks_GetTags_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetTagsRequest, GetTagsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tasks_GetTagsClient = grpc.ServerStreamingClient[GetTagsResponse]

func (c *tasksClient) SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*SetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStatusResponse)
	err := c.cc.Invoke(ctx, Tasks_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksServer is the server API for Tasks service.
// All implementations must embed UnimplementedTasksServer
// for forward compatibility.
type TasksServer interface {
	PutTask(context.Context, *PutTaskRequest) (*PutTaskResponse, error)
	GetTasks(*GetTasksRequest, grpc.ServerStreamingServer[GetTasksResponse]) error
	DescribeTask(context.Context, *DescribeTaskRequest) (*DescribeTaskResponse, error)
	MarkTask(context.Context, *MarkTaskRequest) (*MarkTaskResponse, error)
	GetTags(*GetTagsRequest, grpc.ServerStreamingServer[GetTagsResponse]) error
	SetStatus(context.Context, *SetStatusRequest) (*SetStatusResponse, error)
	mustEmbedUnimplementedTasksServer()
}

// UnimplementedTasksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTasksServer struct{}

func (UnimplementedTasksServer) PutTask(context.Context, *PutTaskRequest) (*PutTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutTask not implemented")
}
func (UnimplementedTasksServer) GetTasks(*GetTasksRequest, grpc.ServerStreamingServer[GetTasksResponse]) error {
	return status.Error(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedTasksServer) DescribeTask(context.Context, *DescribeTaskRequest) (*DescribeTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeTask not implemented")
}
func (UnimplementedTasksServer) MarkTask(context.Context, *MarkTaskRequest) (*MarkTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkTask not implemented")
}
func (UnimplementedTasksServer) GetTags(*GetTagsRequest, grpc.ServerStreamingServer[GetTagsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetTags not implemented")
}
func (UnimplementedTasksServer) SetStatus(context.Context, *SetStatusRequest) (*SetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedTasksServer) mustEmbedUnimplementedTasksServer() {}
func (UnimplementedTasksServer) testEmbeddedByValue()               {}

// UnsafeTasksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TasksServer will
// result in compilation errors.
type UnsafeTasksServer interface {
	mustEmbedUnimplementedTasksServer()
}

func RegisterTasksServer(s grpc.ServiceRegistrar, srv TasksServer) {
	// If the following call panics, it indicates UnimplementedTasksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tasks_ServiceDesc, srv)
}

func _Tasks_PutTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).PutTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tasks_PutTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).PutTask(ctx, req.(*PutTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasks_GetTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TasksServer).GetTasks(m, &grpc.GenericServerStream[GetTasksRequest, GetTasksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tasks_GetTasksServer = grpc.ServerStreamingServer[GetTasksResponse]

func _Tasks_DescribeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).DescribeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tasks_DescribeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).DescribeTask(ctx, req.(*DescribeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasks_MarkTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).MarkTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tasks_MarkTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).MarkTask(ctx, req.(*MarkTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tasks_GetTags_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTagsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TasksServer).GetTags(m, &grpc.GenericServerStream[GetTagsRequest, GetTagsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tasks_GetTagsServer = grpc.ServerStreamingServer[GetTagsResponse]

func _Tasks_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tasks_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServer).SetStatus(ctx, req.(*SetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tasks_ServiceDesc is the grpc.ServiceDesc for Tasks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tasks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tasks.tasks",
	HandlerType: (*TasksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutTask",
			Handler:    _Tasks_PutTask_Handler,
		},
		{
			MethodName: "DescribeTask",
			Handler:    _Tasks_DescribeTask_Handler,
		},
		{
			MethodName: "MarkTask",
			Handler:    _Tasks_MarkTask_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _Tasks_SetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTasks",
			Handler:       _Tasks_GetTasks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTags",
			Handler:       _Tasks_GetTags_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tasks/v1/tasks.proto",
}
